In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as mcolors
import plotly.express as px

In [3]:
air_quality_data = pd.read_csv("Combined data (Nov 2025-Apr 2026).csv")
air_quality_data.head()

,Source.Name,sensor_id,sensor_type,location,lat,lon,timestamp,value_type,value
0,April 2026.csv,4962,pms5003,76,-1.261,36.782,01/04/2026 03:00,P2,8.0
1,April 2026.csv,4962,pms5003,76,-1.261,36.782,01/04/2026 03:00,P1,9.0
2,April 2026.csv,4962,pms5003,76,-1.261,36.782,01/04/2026 03:00,P0,5.0
3,April 2026.csv,4963,DHT22,76,-1.261,36.782,01/04/2026 03:00,humidity,97.2
4,April 2026.csv,4963,DHT22,76,-1.261,36.782,01/04/2026 03:00,temperature,18.4

In [4]:
air_quality_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 548633 entries, 0 to 548632
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Source.Name  548633 non-null  str
 1   sensor_id    548633 non-null  int64
 2   sensor_type  548633 non-null  str
 3   location     548633 non-null  int64
 4   lat          547788 non-null  float64
 5   lon          548633 non-null  float64
 6   timestamp    548633 non-null  str
 7   value_type   548633 non-null  str
 8   value        548551 non-null  float64
dtypes: float64(3), int64(2), str(4)
memory usage: 37.7 MB

In [8]:
air_quality_data.timestamp = pd.to_datetime(air_quality_data.timestamp, format='%d/%m/%Y %H:%M')
air_quality_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 548633 entries, 0 to 548632
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Source.Name  548633 non-null  str
 1   sensor_id    548633 non-null  int64
 2   sensor_type  548633 non-null  str
 3   location     548633 non-null  int64
 4   lat          547788 non-null  float64
 5   lon          548633 non-null  float64
 6   timestamp    548633 non-null  datetime64[us]
 7   value_type   548633 non-null  str
 8   value        548551 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(2), str(3)
memory usage: 37.7 MB

In [9]:
air_quality_data.set_index('timestamp',inplace=True)

In [10]:
air_quality_data.head()

,Source.Name,sensor_id,sensor_type,location,lat,lon,value_type,value
timestamp,,,,,,,,
2026-04-01 03:00:00,April 2026.csv,4962,pms5003,76,-1.261,36.782,P2,8.0
2026-04-01 03:00:00,April 2026.csv,4962,pms5003,76,-1.261,36.782,P1,9.0
2026-04-01 03:00:00,April 2026.csv,4962,pms5003,76,-1.261,36.782,P0,5.0
2026-04-01 03:00:00,April 2026.csv,4963,DHT22,76,-1.261,36.782,humidity,97.2
2026-04-01 03:00:00,April 2026.csv,4963,DHT22,76,-1.261,36.782,temperature,18.4

In [14]:
grouped_aq_values = air_quality_data.groupby('value_type')['value'].rolling(window=3).mean()
grouped_aq_values.head(20)

value_type  timestamp
P0          2026-04-01 03:00:00          NaN
            2026-04-01 03:00:00          NaN
            2026-04-01 03:01:00     8.266667
            2026-04-01 03:01:00    10.933333
            2026-04-01 03:05:00     7.333333
            2026-04-01 03:06:00    10.400000
            2026-04-01 03:07:00     9.733333
            2026-04-01 03:07:00    11.933333
            2026-04-01 03:11:00     9.200000
            2026-04-01 03:12:00     9.533333
            2026-04-01 03:12:00    10.000000
            2026-04-01 03:13:00    10.000000
            2026-04-01 03:17:00     7.666667
            2026-04-01 03:18:00     7.333333
            2026-04-01 03:19:00     8.000000
            2026-04-01 03:23:00     7.666667
            2026-04-01 03:24:00     7.133333
            2026-04-01 03:24:00     5.800000
            2026-04-01 03:28:00     9.133333
            2026-04-01 03:29:00     7.333333
Name: value, dtype: float64